[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
publish = false

[dependencies]
abi = { path = "../lib/abi" }
bootimg = { path = "../lib/bootimg", features = ["write"] }

[dev-dependencies]
proto-wire = { path = "../proto/wire" }
posix-fd = { path = "../lib/posix-fd" }
posix-types = { path = "../lib/posix-types" }
proto-fs = { path = "../proto/fs" }
