[package]
name = "posix-thread-probe"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"

[[bin]]
name = "posix-thread-probe"
test = false
bench = false

[features]
cancel-input = []

[dependencies]
posix-abi = { path = "../../lib/posix-abi", features = ["thread-probe"] }
posix-fs = { path = "../../lib/posix-fs" }
rt = { path = "../../lib/rt", features = ["count-calls"] }
posix-sync = { path = "../../lib/posix-sync" }
posix-clock = { path = "../../lib/posix-clock" }
posix-thread = { path = "../../lib/posix-thread" }
posix-time = { path = "../../lib/posix-time" }
proto-clock = { path = "../../proto/clock" }
proto-wire = { path = "../../proto/wire" }
proto-uart = { path = "../../proto/uart" }
posix-request = { path = "../../lib/posix-request" }
posix-signals = { path = "../../lib/posix-signals" }
process-client = { path = "../../lib/process-client" }
proto-process = { path = "../../proto/process" }
