[package]
name = "kernel"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
description = "The stafeto microkernel"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
abi = { path = "../lib/abi" }
bootimg = { path = "../lib/bootimg" }
kcore = { path = "../kcore" }

[features]
ktest = []
# The kernel tests with those that need `-icount` added (ktest::el0).
icount = ["ktest"]
fault-probe = []
overflow-probe = []
