[package]
name = "posix-clock-service"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"

[[bin]]
name = "posix-clock-service"
test = false
bench = false

[dependencies]
proto-clock = { path = "../../proto/clock" }
proto-wire = { path = "../../proto/wire" }
posix-time = { path = "../../lib/posix-time" }
proto-init = { path = "../../proto/init" }
proto-process = { path = "../../proto/process" }
posix-credentials = { path = "../../lib/posix-credentials" }
rt = { path = "../../lib/rt" }
