[package]
name = "posix-shared-probe"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"

[[bin]]
name = "posix-shared-probe"
test = false
bench = false

[features]
interrupt-probe = ["posix-crt/uart-input"]
input-probe = ["posix-crt/uart-input"]

[dependencies]
posix-abi = { path = "../../lib/posix-abi", features = ["thread-probe"] }
posix-fs = { path = "../../lib/posix-fs" }
posix-crt = { path = "../../lib/posix-crt" }
libc-ffi = { path = "../libc-ffi" }
rt = { path = "../../lib/rt" }
posix-request = { path = "../../lib/posix-request" }
proto-wire = { path = "../../proto/wire" }
proto-uart = { path = "../../proto/uart" }
