[package]
name = "posix-fs"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later"
description = "Rust POSIX file and directory client for stafeto"

[lib]
test = false
bench = false

[dependencies]
posix-path = { path = "../posix-path" }
proto-fs = { path = "../../proto/fs" }
proto-wire = { path = "../../proto/wire" }
rt = { path = "../rt" }
